name: gvxr-validation
channels:
    - conda-forge
dependencies:
    - cma
    - tomopy
    - numpy
    - libtiff
    - pandas
    - ipykernel
    - ipython
    - vtk
    - jupyterlab
    - pandas
    - scikit-learn
    - scikit-image
    - scipy
    - imageio
    - SimpleITK
    - k3d
    - numpy-stl
    - gputil
    - plotly
    - jupyterlab>=3
    - ipywidgets>=7.6
    - python-kaleido
    - pip
    - pip:
        - viewscad
        - spekpy
        - py-cpuinfo
        - pymoo
        - chart_studio
